### ISSUE TITLE
Make it easier to set static options

### ISSUE THREAD

**Issue by heftig** [tikv/jemallocator#15]
I've managed to provide static options to jemalloc in my application via this code:

```rust
#[no_mangle]
pub static mut malloc_conf: *const libc::c_char =
    b"background_thread:true,metadata_thp:auto\0".as_ptr() as _;
```

This isn't very nice, is quite unsafe though no `unsafe` is present, and is dependent on prefixing being disabled. It would be nice if the crate provided a way to set this string in a safe(r) way.

**Comment by BusyJay** [comment]
You can also set it up using environment variable `JEMALLOC_SYS_WITH_MALLOC_CONF`.

**Comment by seanlinsley** [comment]
In either case, how do you confirm that the settings are being used?

**Comment by seanlinsley** [comment]
Okay, I confirmed that it's reaching jemalloc by setting it to an invalid string and then getting `<jemalloc>: Conf string ends with key` at runtime.

Assuming you've already installed jemalloc at this point `cargo clean -p jemalloc-sys` is needed because the environment variable is only used when the crate is compiled. Then set the environment variable before the next compile. For example from https://github.com/tokio-rs/tokio/issues/2479#issuecomment-623157381

```sh
cargo clean -p jemalloc-sys
export JEMALLOC_SYS_WITH_MALLOC_CONF="background_thread:true,narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true"
cargo build
```

**Comment by BusyJay** [comment]
> `cargo clean -p jemalloc-sys` is needed because the environment variable is only used when the crate is compiled

Interesting. I think it should be a bug of jemalloc-sys's build script. It should hint cargo to watch the environment variable.
